### ISSUE TITLE
Order of operations

### ISSUE THREAD

**Issue by weierophinney** [tuupola/cors-middleware#1]
Hi! An Expressive user was using your middleware recently, and couldn't figure out why the CORS headers were not being set. In the end, they realized that they were creating a response within a lower layer and returning it:

```php
return new JsonResponse($data);
```

The problem is that cors-middleware injects the response that it passes to `$next()` - which means the headers are then lost if an inner layer creates and returns a new response instance.

I suggest that the following lines:

- https://github.com/tuupola/cors-middleware/blob/096f83b7e1a3485e5b34b8029360d7ac246eef14/src/Cors.php#L86-L93

be updated to operate on the *returned* response instead. This will guarantee they are injected.

**Comment by tuupola** [comment]
You are correct. Thanks for the heads up!

**Comment by grizzm0** [comment]
Any ETA for a fix?

I'm not quite sure what @weierophinney meant by operate on the returned response. Else I would have created a PR myself.

**Comment by derpoho** [comment]
@tuupola Also ran into this issue now. Do you have any ETA?

**Comment by grizzm0** [comment]
Ah! I was supposed to PR this but totally forgot about it. :p Currently on vacation... But I'll see if I get the time to create the PR tomorrow.

**Comment by tuupola** [comment]
@grizzm0 Actually no need to. I just returned from holidays and will check this out.

**Comment by tuupola** [comment]
@grizzm0 @derpoho can you test if `0.5.2` fixes your problem.

**Comment by grizzm0** [comment]
Yeah, that fixed it. Thanks!
