### ISSUE TITLE
Breaking changes, please tag a new version

### ISSUE THREAD

**Issue by bluebaroncanada** [tuupola/cors-middleware#13]
https://github.com/tuupola/cors-middleware/commit/b042f9da6a14a98bd9aa0e5396a811f548cc112e breaks.

It's actually incompatible with zend-expressive because zend-expressive hard-requires 0.41 because psr-15 hasn't been accepted yet.  It  should be accepted in a later release.
Even if you don't agree with that, which you definitely should, you should've at least tagged it.

This is a major issue right now.

See for more information
https://discourse.zendframework.com/t/psr-15-compatibility-issues-and-proposal/378

**Comment by tuupola** [comment]
https://github.com/tuupola/cors-middleware/blob/master/CHANGELOG.md

It was tagged as `0.6.0`. There is no stable `1.x` release yet so breaking changes can happen with minor version numbers. After stable release breaking changes only happen with major version numbers. I did not test but I assume the previous `0.5.2` version should still work with Expressive?
