### ISSUE TITLE
Multiple origins with wildcards

### ISSUE THREAD

**Issue by amandiobm** [tuupola/cors-middleware#14]
Hi guys, I read all the code but is not clear to me. This middleware supports multiple origins with wildcards.

Example: `[ 'https://*.domain.com', 'https://*.domainmagic.com' ]`

Best regards.

**Comment by MainaWycliffe** [comment]
Hi, did you ever verify whether it woeks like that?

**Comment by tuupola** [comment]
AFAIK no, but maybe @neomerx can also confirm?

**Comment by neomerx** [comment]
You're probably talking about 'allowed origins' for CORS requests.  The default implementation does not support wildcards (other than special wildcard meaning `all origins`). However, if you so desire you can absolutely do it. It will require overriding `SettingsStrategyInterface::isRequestOriginAllowed` with implementation that fits your needs (here is [default](https://github.com/neomerx/cors-psr7/blob/24944f39483d1a89f66ae9d58cca9f82b8815b35/src/Strategies/Settings.php#L217-L229)) and inject the new settings strategy as shown in the [documentation](https://github.com/neomerx/cors-psr7#advanced-usage).

**Comment by MainaWycliffe** [comment]
That's what i did finally

**Comment by amandiobm** [comment]
> You're probably talking about 'allowed origins' for CORS requests. The default implementation does not support wildcards (other than special wildcard meaning all origins). However, if you so desire you can absolutely do it. It will require overriding SettingsStrategyInterface::isRequestOriginAllowed with implementation that fits your needs (here is default) and inject the new settings strategy as shown in the documentation.

Yes it's about the origin CORS with wildcards. Now I realize that my example was missing the '*'. Sorry guys.  :(

@MainaWycliffe  you will make and PR with this feature?

**Comment by MainaWycliffe** [comment]
@amandiobm Yes, I will work on it. Where a user provides several CORS allowed origin and the middleware just checks the current origin `$_SERVER['HTTP_ORIGIN']` against the list provided and if it exists, then it is returned as the allowed origin and if not, it returns no origin.

**Comment by neomerx** [comment]
@MainaWycliffe that's default implementation for `SettingsStrategyInterface::isRequestOriginAllowed`. You probably want to match against wildcards (regular expressions?). Method `SettingsStrategyInterface::isRequestOriginAllowed` should return `bool` true/false but not just `no origin`.

**Comment by amandiobm** [comment]
@MainaWycliffe any updates?!?! If you need some help i'm here ;))

**Comment by MainaWycliffe** [comment]
@amandiobm Not yet, got caught up too much last week. I have been looking at it today and trying to come up with the best way to solve this particular issue. I will give you an update you as soon as I can and incase i need help i will ask, thanks.

**Comment by MainaWycliffe** [comment]
@amandiobm and @tuupola correct me if am wrong but after dissecting the code, it seems that the only way for this to achieve multi wildcard origin is by editing the middleware which it uses from @neomerx and not this library?

**Comment by tuupola** [comment]
Correct. That is what @neomerx also mentioned in the [comment above](https://github.com/tuupola/cors-middleware/issues/14#issuecomment-363732180).

**Comment by neomerx** [comment]
I would change [buildSettings method](https://github.com/tuupola/cors-middleware/blob/b0e2b7acacf22acae6ba029ee424fd6c073bb443/src/CorsMiddleware.php#L130-L157) so it would return custom `SettingsInterface`.

I guess, nearly complete solution below

```php
    private function buildSettings(ServerRequestInterface $request, ResponseInterface $response): SettingsStrategyInterface
    {
        $settings = new class extends Settings
        {
            /**
             * @inheritdoc
             */
            public function isRequestOriginAllowed(ParsedUrlInterface $requestOrigin)
            {
                $isAllowed = parent::isRequestOriginAllowed($requestOrigin);

                // if origin is not on the list of allowed let's check it by mask(s)
                if ($isAllowed === false) {
                    $origin = (string)$requestOrigin;

                    // of course should not be hardcoded but taken from settings
                    $pattern = '/^\S+good-host.com$/i';

                    $isAllowed = preg_match($pattern, $origin) === 1;
                }

                return $isAllowed;
            }
        };

        // the rest is the same as in the current version

        return $settings;
    }
```

**Comment by MainaWycliffe** [comment]
Nice Idea @neomerx, I have run through it but after playing preg_match for sometime, where I tried to replace the wildcard with an equivalent REGEX String, I didn't have much success there. Instead I had success using php fnmatch [function](http://php.net/manual/en/function.fnmatch.php), and It worked brilliantly since it accepts wildcards. The only major issue is that it doesn't work in all Operating Systems but support may becoming latter.

**Comment by neomerx** [comment]
I think regular expressions would be the right way to go due to their flexibility and support. Developers will find a way to write them. I guess any number of 'masks' could be written in one regular expression however it might become too large. For this reason, I would support multiple expressions

```php
                // should be taken from settings
                $patterns = ['/^\S+good-host.com$/i'];

                if ($isAllowed === false && empty(patterns) === false) {
                    $origin = (string)$requestOrigin;

                    foreach ($patterns as $pattern) {
                        if (preg_match($pattern, $origin) === 1) {
                            $isAllowed = true;
                            break;
                        }
                    }
                }
```

There are plenty of online regex tools [like this one](https://regex101.com/)
![image](https://user-images.githubusercontent.com/10420662/36419222-5506f1a2-1642-11e8-9b5b-1019f7715b12.png)

**Comment by MainaWycliffe** [comment]
Thanks for that, I finally managed to use regular expressions. I replaced all wildcard characters with the REGEX equivalent .* and it works as expected. Here is part of the snippet i ran the tests with:

```
                $pattern = preg_quote($domain, '/');
                $pattern = str_replace('\*', '.*', $pattern);
                //$pattern = preg_replace('/\\*+/', '*', $pattern);

                if (preg_match('/^' . $pattern . '$/i', $origin)) {
                    echo "TRUE Origin " . $origin . " is allowed for " . $domain . " <br>";
                } else {
                    echo "FALSE Origin " . $origin . " is not allowed for " . $domain . " <br>";
                }
```

I also used the tool you provided above to confirm my theory and it works brilliantly. Let me see now I can repackage the middleware.

**Comment by MainaWycliffe** [comment]
I am assuming this snippet here is where you check whether wildcard is allowed (In the original `isRequestOriginAllowed` method under Settings)

` $isAllowed = isset($this->settings[self::KEY_ALLOWED_ORIGINS][$requestOriginStr]);`

Can you confirm that this is `$this->settings[self::KEY_ALLOWED_ORIGINS]` an array? I am thinking of comparing each allowed origin with current origin until i find a match.

**Comment by neomerx** [comment]
It is an array however internally however it's expected you will work with those data directly.

I'd rather just add a new setting to [options](https://github.com/tuupola/cors-middleware/blob/b0e2b7acacf22acae6ba029ee424fd6c073bb443/src/CorsMiddleware.php#L38-L46) such as `origin.allow.regex`

it will cause [hydrate method](https://github.com/tuupola/cors-middleware/blob/b0e2b7acacf22acae6ba029ee424fd6c073bb443/src/CorsMiddleware.php#L110) to call method `originAllowRegex` which should be added to [CorsMiddleware](https://github.com/tuupola/cors-middleware/blob/b0e2b7acacf22acae6ba029ee424fd6c073bb443/src/CorsMiddleware.php#L33)

the method might look like

```php
    private function originAllowRegex(array $origins): void
    {
        $this->options['origin.allow.regex'] = $origins;
    }
```

and finally

```php
    private function buildSettings(ServerRequestInterface $request, ResponseInterface $response): SettingsStrategyInterface
    {
        $settings = new class ($this->options['origin.allow.regex']) extends Settings
        {
            private $patterns;

            public function __construct($patterns)
            {
                $this->patterns = $patterns;
            }

            /**
             * @inheritdoc
             */
            public function isRequestOriginAllowed(ParsedUrlInterface $requestOrigin)
            {
                $isAllowed = parent::isRequestOriginAllowed($requestOrigin);

                // if origin is not on the list of allowed let's check it by mask(s)
                if ($isAllowed === false && empty($patterns) === false) {
                    $origin = (string)$requestOrigin;

                    foreach ($this->patterns as $pattern) {
                        if (preg_match($pattern, $origin) === 1) {
                            $isAllowed = true;
                            break;
                        }
                    }
                }

                return $isAllowed;
            }
        };

        // the rest is the same as in the current version

        return $settings;
    }
```

And that's pretty much it. Now it would be possible to have an array of regex in 'origin.allow.regex' of the settings.

**Comment by tuupola** [comment]
I can already tell this is awfully a lot of code to maintain for a rare(ish) use case. I probably just add a way for user to pass a custom instance of `neomerx/cors-psr7` in the middleware constructor. This way the middleware covers all the possible use cases. Something like:

```php
use \Neomerx\Cors\Analyzer;

...

$app->add(new Tuupola\Middleware\CorsMiddleware([
    "analyzer" =>  Analyzer::instance($settings)
]));

**Comment by MainaWycliffe** [comment]
From what I can tell, even the `neomerx/cors-psr7` is not able to use wildcards for origin comparison. Instead you have to provide a list of all origins and be an exact match.

**Comment by neomerx** [comment]
> even the neomerx/cors-psr7 is not able to use wildcards for origin comparison. 

:man_facepalming: 

neomerx/cors-psr7 provides [a way to inject any implementation for origin comparison](https://github.com/neomerx/cors-psr7#advanced-usage) that fits your app. And I have shown above how to use it.

**Comment by tuupola** [comment]
Correct, but as @neomerx has explained before you can instantiate `neomerx/cors-psr7` with a custom `SettingsStrategyInterface` which handles the wildcards.

**Comment by MainaWycliffe** [comment]
Excellent and thank you @neomerx for all your help

**Comment by amandiobm** [comment]
Hello guys, long time no see.

There is any updates?!?!

**Comment by amandiobm** [comment]
Hey guys, this still on development? on hold? Any updates?!

Tks.

**Comment by OssiPesonen** [comment]
The solution is to do the following (I'm hoping to open a PR later). This is Slim Framework implementation and I've extended the middleware. As @neomerx told you above, you have to create a custom class which extends the Neomerx Settings:

```php
class CustomCorsSettings extends \Neomerx\Cors\Strategies\Settings {
    public function isRequestOriginAllowed(\Neomerx\Cors\Contracts\Http\ParsedUrlInterface $requestOrigin): bool  {
        // Check if all origins are allowed with '*'
        $isAllowed = isset($this->settings[self::KEY_ALLOWED_ORIGINS][\Neomerx\Cors\Contracts\Constants\CorsResponseHeaders::VALUE_ALLOW_ORIGIN_ALL]);

        if ($isAllowed === false) {
            $requestOriginStr = strtolower($requestOrigin->getOrigin());
            $isAllowed        = isset($this->settings[self::KEY_ALLOWED_ORIGINS][$requestOriginStr]);
        }

        return $isAllowed;
    }
}
```

The `isRequestOriginAllowed` above is a copy of the same implementation that the Neomerx contains, so don't just do this, but rather extend the method. Like he told you above, perhaps add a regular expression check for wildcards?

Now, I passed this to `CorsMiddleware` in a `settings` key:

```php
$app->add(new Tuupola\Middleware\CorsMiddleware([
   ...
   'settings' => CustomCorsSettings::class
]);
````
After this I had to extend the `CorsMiddleware.php`

```php
    /**
     * Build a CORS settings object.
     */
    private function buildSettings(ServerRequestInterface $request, ResponseInterface $response): CorsSettings
    {
        // Custom CorsSettings
        if($this->options['settings'])
        {
            $corsSettings = new $this->options['settings']();

            if ($corsSettings instanceof CorsSettings) {
                $settings = $corsSettings;
            }
        }

        $settings = $settings ?? new CorsSettings;
       ...
```

I did some manual testing and the checks pass through the overwritten `isRequestOriginAllowed` method.

**Comment by tuupola** [comment]
There really is not any solution to this I would be 100% happy with. 

Passing the `Analyzer` instance in options would be easiest code wise but it is cumbersome for the user. Passing classname of custom `Settings` instance is also a good idea but it requires user to write his or hers own settings class. Internally using custom `Settings` implementation which supports regexps is the easiest for the user but requires me to support the code for it.

That said, I believe the middleware should be as easy as possible for users to use. Because of this I am currently leaning on creating an internal `Settings` class which supports regexps. More code to maintain but easiest for the user.

**Comment by mikhailidi** [comment]
Any progress on this issue?

**Comment by mikhailidi** [comment]
@tuupola any updates?
