### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Tuupola\\Middleware\\Cors' 

### ISSUE THREAD

**Issue by newbie14** [tuupola/cors-middleware#17]
I am trying to implement you full codes for the sample of JWT at this link https://trinitytuts.com/secure-your-php-web-services-using-jwt/.
Just after inserting the middleware codes and I just try to run my root path I saw this error in my apache logs.
PHP Fatal error:  Uncaught Error: Class 'Tuupola\\Middleware\\Cors' not found in /var/www/html/api/src/middleware.php:53\nStack trace:

**Comment by tuupola** [comment]
https://github.com/tuupola/cors-middleware#usage
https://github.com/tuupola/cors-middleware/blob/master/CHANGELOG.md

Latest version of the middleware has different classname `Tuupola\Middleware\CorsMiddleware`.

**Comment by newbie14** [comment]
Hi Tuupola,
                  Thank you I just set to this $app->add(new Tuupola\Middleware\CorsMiddleware it works. In addition how could I further harden this settings for cors to help protect my apis?  Another thing how is this work $app->add(new \Slim\Middleware\HttpBasicAuthentication([
    "path" => "/api/token",
    "users" => [
        "user" => "password"
    ]
]));
I dont get this section ? How is user password decided ?

**Comment by tuupola** [comment]
Whatever you decide yourself. To have an user `newbie14` with password `s3cr3t` you would use:

```
"users" => [
    "newbie14" => "s3cr3t"
]
```

In any case this place is for bug reports of the cors middleware. For general programming help (Slim forums)[http://discourse.slimframework.com/] and [StackOverflow](https://stackoverflow.com/) is a better place.
