### ISSUE TITLE
Fatal error: Uncaught Error: Class not found.

### ISSUE THREAD

**Issue by jardelsimao** [tuupola/cors-middleware#19]
I tried to install this plugin but I got this error:

Fatal error: Uncaught Error: Class 'Slim\Middleware\CorsMiddleware' not found in.

How I solve this

files:

-> apirestful
-> src
     middleware.php
-> vendor
     -> tuupola
        -> cors-middleware

---------------------------------------------------------------------------
And my middleware.php:

```
<?php

use Tuupola\Middleware\CorsMiddleware;

$settings = $app->getContainer()->get('settings');

$app->add(new \Tuupola\Middleware\CorsMiddleware);

$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => "/api", /* or ["/api", "/admin"] */
    "secret" => $settings['jwt']['secret'],
    "algorithm" => ["HS256"],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    },
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));
?>
```
----------------------------------------------------------------------------
composer.json

    "require": {
        "php": ">=5.5.0",
        "slim/slim": "^3.9",
        "slim/php-view": "^2.0",
        "monolog/monolog": "^1.17",
        "tuupola/slim-jwt-auth": "^2.3",
        "tuupola/base62": "^0.9.0",
        "tuupola/cors-middleware": "^0.5.2"
    },

**Comment by tuupola** [comment]
Check at the line number which should be in the end of the error message

```
Fatal error: Uncaught Error: Class 'Slim\Middleware\CorsMiddleware' not found in.
```

In that line change to the correct classname `Tuupola\Middleware\CorsMiddleware`.

**Comment by jardelsimao** [comment]
Sorry, I tried something changes but nothing happens.

Fatal error: Uncaught Error: Class 'Tuupola\Middleware\CorsMiddleware' not found in C:\wamp\www\apirestful\src\middleware.php on line 10

**Comment by tuupola** [comment]
Ah looking at your composer.json you have old version installed.

https://github.com/tuupola/cors-middleware/blob/master/CHANGELOG.md

Ie. use old classname `Tuupola\Middleware\Cors`

**Comment by jardelsimao** [comment]
I Changed and got this error:

`use Tuupola\Middleware\Cors;

$settings = $app->getContainer()->get('settings');

$app->add(new \Tuupola\Middleware\Cors);
$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => "/api", /* or ["/api", "/admin"] */
    "secret" => $settings['jwt']['secret'],
    "algorithm" => ["HS256"],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    },
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));`

`Warning: Missing argument 1 for Tuupola\Middleware\Cors::__construct(), called in C:\wamp\www\apirestful\src\middleware.php on line 10 and defined in C:\wamp\www\apirestful\vendor\tuupola\cors-middleware\src\Cors.php on line 42`

`Notice: Undefined variable: options in C:\wamp\www\apirestful\vendor\tuupola\cors-middleware\src\Cors.php on line 47`

`
TypeError: Argument 1 passed to Tuupola\Middleware\Cors::hydrate() must be of the type array, null given, called in C:\wamp\www\apirestful\vendor\tuupola\cors-middleware\src\Cors.php on line 47 in C:\wamp\www\apirestful\vendor\tuupola\cors-middleware\src\Cors.php on line 105
`

**Comment by tuupola** [comment]
> Warning: Missing argument 1 for Tuupola\Middleware\Cors::__construct()
> TypeError: Argument 1 passed to Tuupola\Middleware\Cors::hydrate() must be of the type array, null given

I think the old version required you to pass something to the constructor. If you do not have any config, instead of giving null, give an empty array.

```php
$app->add(new \Tuupola\Middleware\Cors([]));
```

**Comment by jardelsimao** [comment]
Yes, I solved using this code:

```
$app->add(new \Tuupola\Middleware\Cors([
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    "headers.allow" => [],
    "headers.expose" => [],
    "credentials" => false,
    "cache" => 0,
]));
```
Thank you

**Comment by Gacci** [comment]
I have the same problem but it seems like everything is up-to-date.

This is my composer.json
```
{
    "require": {
        "slim/slim": "~3.0",
        "illuminate/database": "~5.0",
        "illuminate/pagination": "^5.6",
        "tuupola/slim-jwt-auth": "^3.0",
        "guzzlehttp/psr7": "^1.4",
        "snicholson/slimfilecache": "~1.0",
        "vlucas/phpdotenv": "^2.4",
        "tuupola/cors-middleware": "^0.9.1"
    },
    "autoload": {
    	"psr-4": {
    		"App\\": "app"
    	}
    }
}

```


This is what I have
```
$app->add(new Tuupola\Middleware\JwtAuthentication([ 
	"secret" => getenv("SECRET")
	, "algorithm" => ["HS256"]
	, "cookie" => "JWT"
	, "regexp" => "/.+/"
	, "secure" => false
	, "error" => function ($response, $arguments) {
        return $response->withStatus(401, $arguments["message"]);
    }
    , "rules" => [
	    new Tuupola\Middleware\JwtAuthentication\RequestPathRule(["path" => "/"
	    		, "ignore" => ["/users/signin", "/users/signup", "/users/recover"
				, "/users/confirm", "/users/recognize", "/colleges/*", "/stats/*"
			]
	    ])
	]
]));

$app->add(new Tuupola\Middleware\CorsMiddleware([
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    "headers.allow" => [],
    "headers.expose" => [],
    "credentials" => false,
    "cache" => 0,
]));
```

This is the error:
```
Fatal error: Uncaught Error: Class 'Tuupola\Middleware\CorsMiddleware' not found in /hermes/bosnaweb23a/b185/ipg.jenjeloocom/v3.0/bootstrap/app.php:70
Stack trace:
#0 /hermes/bosnaweb23a/b185/ipg.jenjeloocom/v3.0/public/index.php(3): require()
#1 {main}
  thrown in /hermes/bosnaweb23a/b185/ipg.jenjeloocom/v3.0/bootstrap/app.php on line 70

```


`Tuupola\Middleware\JwtAuthentication` is working just fine.

Thank you.

**Comment by tuupola** [comment]
@Gacci Either you have not installed the CORS Middleware or you could be running version older than [0.6.0](https://github.com/tuupola/cors-middleware/blob/master/CHANGELOG.md#060---2017-12-25).

**Comment by Gacci** [comment]
@tuupola I believe is installed properly; I am able to see the folder and its contents along with the other Middleware of yours I am using (each middleware in its respective folder). As for the version, I believe I installed 0.9.1 as shown in the composer.json file.  Am I wrong on any of these?

**Comment by tuupola** [comment]
You can use `$ composer show --installed` to show which versions of libraries are installed. The installed version number does not necessarily exactly match what is in `composer.json`.

**Comment by Gacci** [comment]
Thank you, I solved the problem.
