### ISSUE TITLE
Same-Origin requests are blocked when Origin header is present

### ISSUE THREAD

**Issue by fabacino** [tuupola/cors-middleware#22]
If a same-origin request is sent with an (unnecessary) origin header, the middleware blocks the request unless the server origin is explicitly added to the allowed origins. This is afaik not technically wrong, but still needs to be handled manually when using the middleware, since at least Chrome sends these unnecessary origin headers all the time.

```php
$app->add(new \Tuupola\Middleware\CorsMiddleware([
    'origin' => []
]));
```

```bash
curl --request POST 'https://www.example.com'
     --include
     --header 'Origin: https://www.example.com'
```

```
HTTP/1.1 401 Unauthorized
Date: Tue, 14 Aug 2018 14:36:45 GMT
Server: Apache/2.4.34 (Unix) OpenSSL/1.1.0h PHP/7.2.8
X-Powered-By: PHP/7.2.8
Content-Length: 0
```

I think it would be nice if the middleware provided an additional option to pass a value for the server origin to the `Strategies\Settings` class of the underlying neomerx/cors-psr7 library (there already exists a function `setServerOrigin` in that class).

I can PR if you think this might be useful.

**Comment by tuupola** [comment]
I did not test myself yet, but sounds like a bug. PR would be great! The option name could be something like `origin.server`.
