### ISSUE TITLE
OPTIONS request gets a "401 Unauthorized" response

### ISSUE THREAD

**Issue by EmreErdogan** [tuupola/cors-middleware#3]
I use the following configuration for setting up CORS.

```
$app->add(new \Tuupola\Middleware\Cors([
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    "headers.allow" => [],
    "headers.expose" => [],
    "credentials" => false,
    "cache" => 0,
]));
```

When I send a POST request with AngularJS, first a preflight OPTIONS is sent. Then I got stuck with a 401 Unauthorized response. So, POST request can never be sent.

I tried adding "OPTIONS" to into methods parameter in the configuration, but nothing changes. Am I missing something or doing it wrong?

**Comment by tuupola** [comment]
You can add a logger and check from there what makes the CORS request fail.

https://github.com/tuupola/cors-middleware#logger

**Comment by EmreErdogan** [comment]
Thanks for the advice. I set the error config then I got the following response: 
```

{
    "status": "error",
    "message": "CORS requested header is not allowed."
}
```

Does that mean I should write down every request header into `"headers.allow"`?

**Comment by tuupola** [comment]
Only the headers which you request via the `Access-Control-Request-Headers` header.

**Comment by EmreErdogan** [comment]
@tuupola I added `"Content-type"` into `"headers.allow"`. It worked.

My final configuration is below.

```
$app->add(new \Tuupola\Middleware\Cors([
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    "headers.allow" => ["Content-type"],
    "headers.expose" => [],
    "credentials" => false,
    "cache" => 0,
]));
```

Thanks @tuupola

**Comment by mahcello** [comment]
Been looking for this a long time!
Totally worked!
