### ISSUE TITLE
Update neomerx/cors-psr7 to v2

### ISSUE THREAD

**Issue by internalsystemerror** [tuupola/cors-middleware#33]
Version 2 is out https://github.com/neomerx/cors-psr7/tree/v2.0.2. I can see you're already ahead on this: https://github.com/neomerx/cors-psr7/issues/32. Just wanted to give you the heads up.

**Comment by Rodrirokr** [comment]
As a side note on the neomerx/cors-psr7 update, I've detected a bug in the method 
 `Analizer->getRequestedHeadersInLowerCase($request)` it only gets the first of the methods of the request, so at the implementation of the method `isRequestAllHeadersSupported` of the `AnalysisStrategyInterface` interface  in version v1.0.13 of neomerx/cors-psr7, only the first header of the request is checked against the `headers.allow` array of the `CorsMiddleware` configuration options. The version 2.x effectively corrects the issue with a `forEach` loop of all the request headers.
