### ISSUE TITLE
CorsMiddleware->process() creates a response even tough its passed a response object

### ISSUE THREAD

**Issue by Rodrirokr** [tuupola/cors-middleware#37]
Hi! I'm really enjoying your project, thank you very much.

I have a question about, why in `CorsMiddleware->process(ServerRequestInterface $request, RequestHandlerInterface $handler)` there's an instantiation of a response object?

That's because in the $handler that is instantiated in `DoublePassTrait->__invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next)` already has a response as a property.

This instantiated response inside `CorsMiddleware->process(...)` is used in all cases except in the actual CORS request, why in this case is used the request property from the handler?

I think I'm missing something, it would be very enlightening if you could response these questions.

**Comment by tuupola** [comment]
This middleware uses [PSR-15](https://www.php-fig.org/psr/psr-15/) standard which does not pass the `$response` object to the handler. The `DoublePassTrait` is an adapter so that it can be used also with frameworks which support only the older style double pass middlewares.
