### ISSUE TITLE
Cannot set my own header

### ISSUE THREAD

**Issue by ozzpy** [tuupola/cors-middleware#38]
I have an angular app that use a specific header (name:content) to check it on server,
After configure the corsMiddleware to allow it, I still got an error : `Request header field headerMyApp is not allowed by Access-Control-Allow-Headers in preflight response.`

I allow it inn my middeware pipeline 

```php
$app->pipe(new CorsMiddleware([
            "origin" => ["*"],
            "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE","OPTIONS"],
            "headers.allow" => ["Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With","headerMyApp"],
            "headers.expose" => ["Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With","headerMyApp"]
    ]));
```

**Comment by tuupola** [comment]
Have you checked what is the content of `Access-Control-Allow-Headers` header in the response?
