### ISSUE TITLE
Uncaught BadMethodCallException

### ISSUE THREAD

**Issue by wilfredcom** [tuupola/cors-middleware#39]
I recently installed the middleware and added the lines acording to the documentation, but it fails with the following error:

 PHP Fatal error:  Uncaught BadMethodCallException: Method pipe is not a valid method in /var/www/vendor/slim/slim/Slim/App.php:125\nStack trace:\n#0 /var/www/public/index.php(16): Slim\\App->__call('pipe', Array)\n#1 {main}\n  thrown in /var/www/vendor/slim/slim/Slim/App.php on line 125

mi index.php looks like:

```
require __DIR__ . '/../vendor/autoload.php';
use Tuupola\Middleware\CorsMiddleware;
// Instantiate the app
$settings = require __DIR__ . '/../src/settings.php';
$app = new \Slim\App($settings);
$database = require __DIR__ . '/../src/settingsDB.php';
// Set up dependencies
$dependencies = require __DIR__ . '/../src/dependencies.php';
$dependencies($app);
$app->pipe(CorsMiddleware::class);
$app->add(new Tuupola\Middleware\CorsMiddleware);
// Register middleware
$middleware = require __DIR__ . '/../src/middleware.php';
$middleware($app);
// Register routes
$routes = require __DIR__ . '/../src/routes.php';
$routes($app);
```
Thanks and sorry if it's a newbie and easy question.

**Comment by tuupola** [comment]
Slim does not have a `pipe()` method. Instead it uses `add()` as a method for adding middleware.
