### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Slim\Slim::pipe()

### ISSUE THREAD

**Issue by rubenssb** [tuupola/cors-middleware#43]
Cors Middleware is normally installed with composer.

My index.php of API is:

```

<?php

$loader = require 'vendor/autoload.php';


//Consults Routes
$app = new \Slim\Slim(array(
    'templates.path' => 'templates'
));


use Tuupola\Middleware\CorsMiddleware;

#$app->pipe(ImplicitOptionsMiddleware::class);
$app->pipe(CorsMiddleware::class);



$app->add(new Tuupola\Middleware\CorsMiddleware([
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    "headers.allow" => [],
    "headers.expose" => [],
    "credentials" => false,
    "cache" => 0,
]));


$app->get('/consults/', function() use ($app){
	(new \controllers\Consults($app))->list();
});

$app->get('/consults/:id', function($id) use ($app){
	(new \controllers\Consults($app))->get($id);
});

$app->post('/consults/', function() use ($app){
	(new \controllers\Consults($app))->new();
});

$app->put('/consults/:id', function($id) use ($app){
	(new \controllers\Consults($app))->edit($id);
});

$app->delete('/consults/:id', function($id) use ($app){
	(new \controllers\Consults($app))->delete($id);
});



//Vehicles Routes
$app->get('/vehicles/', function() use ($app){
	(new \controllers\Vehicles($app))->list();
});

$app->get('/vehicles/:id', function($id) use ($app){
	(new \controllers\Vehicles($app))->get($id);
});

$app->get('/vehicles-top/', function() use ($app){
	(new \controllers\Vehicles($app))->listTop();
});

$app->post('/vehicles/', function() use ($app){
	(new \controllers\Vehicles($app))->new();
});

$app->put('/vehicles/:id', function($id) use ($app){
	(new \controllers\Vehicles($app))->edit($id);
});

$app->delete('/vehicles/:id', function($id) use ($app){
	(new \controllers\Vehicles($app))->delete($id);
});

$app->put('/vehicles/:id', function($id) use ($app){
	(new \controllers\Vehicles($app))->incrementConsult($id);
});

$app->run();
```

I have a error with the line 
```
$app->pipe(CorsMiddleware::class);
```

Fatal error: Uncaught Error: Call to undefined method Slim\Slim::pipe() in C:\wamp64\www\tabela-fipe\backend\tabelafipe-backend\api\index.php on line 15

Is slim the problem here?

**Comment by tuupola** [comment]
Slim does not have `pipe()` method. Instead it uses `add()`.

```php
$app->add(new Tuupola\Middleware\CorsMiddleware);
```

**Comment by rubenssb** [comment]
Thanks, @tuupola 

Now, I have this error with the line above:
```
$app->add(new Tuupola\Middleware\CorsMiddleware);
```
**Error:** Fatal error: Uncaught Error: Class 'Tuupola\Middleware\CorsMiddleware' not found



If, I change the class to Cors, I have other error:
```
$app->add(new Tuupola\Middleware\Cors);
```
**Error:** Fatal error: Uncaught TypeError: Argument 1 passed to Slim\Slim::add() must be an instance of Slim\Middleware, instance of Tuupola\Middleware\Cors given...

**Comment by tuupola** [comment]
You have installed old version [0.5.2](https://github.com/tuupola/cors-middleware/blob/master/CHANGELOG.md#052---2016-08-12) or older. Try again with the [latest](https://github.com/tuupola/cors-middleware/blob/master/CHANGELOG.md#110---2019-10-08). For this you need PHP 7.1 or higher.

**Comment by tuupola** [comment]
Looking at the error message:

```
Error: Fatal error: Uncaught TypeError: Argument 1 passed to Slim\Slim::add() must be an instance of Slim\Middleware, instance of Tuupola\Middleware\Cors given...
```

Are you running Slim 2? It is not supported. This middleware can be used with Slim 3 or higher.

**Comment by rubenssb** [comment]
@tuupola 
I checked here and my PHP version is 7.2.18. I'm using WAMP server locally.

My Slim version is 3.12.2

**Comment by tuupola** [comment]
Ok. I would try installing the latest version of middleware. Judging from the classname you have  [0.5.2](https://github.com/tuupola/cors-middleware/blob/master/CHANGELOG.md#052---2016-08-12) or older.
