### ISSUE TITLE
CORS issues with The PHP League Route

### ISSUE THREAD

**Issue by guilherme90** [tuupola/cors-middleware#47]
I'm having CORS issues using the https://route.thephpleague.com/ library

My current config: https://gist.github.com/guilherme90/f8cfd339fbdf2562013030d679f971a8

### cURL with OPTIONS
```
curl -X OPTIONS "http://127.0.0.1:8000/api/contacts/1" --include --header "Access-Control-Request-Method: OPTIONS" --header  "Origin: http://10.0.0.184:8080"
```

### Response cURL
```
HTTP/1.1 200 OK
Host: 127.0.0.1:8000
Date: Wed, 11 Mar 2020 19:14:38 GMT
Connection: close
X-Powered-By: PHP/7.3.9
Access-Control-Allow-Origin: http://10.0.0.184:8080
Vary: Origin
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Content-type: text/html; charset=UTF-8
```
### cURL with GET
```
curl "http://127.0.0.1:8000/api/contacts/1" --include --header "Access-Control-Request-Method: OPTIONS" --header "Origin: http://10.0.0.184:8080"
```

### Response cURL
```
HTTP/1.1 200 OK
Host: 127.0.0.1:8000
Date: Wed, 11 Mar 2020 19:19:02 GMT
Connection: close
X-Powered-By: PHP/7.3.9
Content-Type: application/json
Access-Control-Allow-Origin: http://10.0.0.184:8080
Vary: Origin

{"data":[], "offset":0,"currentPage":1,"perPage":20,"pages":0,"total":0}
```

But when I apply with Axios, gives me this problem. Any idea about that ? 
Thanks

**Comment by tuupola** [comment]
What kind of problem do you have with Axios? I would check the JavaScript console to see what kind of request Axios is doing.

**Comment by guilherme90** [comment]
I don't know if it's exactly with Axios, but it gives Cors  problem. And the worst I did the test on Chrome and Firefox. The problem is in both.

![Screenshot_1](https://user-images.githubusercontent.com/2879939/76528848-37875a00-6450-11ea-9c72-35bfb18db8e7.png)

![Screenshot_2](https://user-images.githubusercontent.com/2879939/76528849-381ff080-6450-11ea-9398-665c77948a57.png)

**Comment by guilherme90** [comment]
Solved. It was a configuration parameter in the headers of Axios.

Thanks for help me.
Cheers!
