### ISSUE TITLE
Debug option

### ISSUE THREAD

**Issue by ybelenko** [tuupola/cors-middleware#48]
I've noticed logger instance in your source code:
https://github.com/tuupola/cors-middleware/blob/832bbf0521a7054c202da15cf05ff2101b152f94/src/CorsMiddleware.php#L55

But it seems to me that there is no way to set this logger with options or somewhere else.
This middleware doesn't work with OPTIONS http method on my local Apache(Slim4) server, so it would be great to have any debug option.

**Comment by tuupola** [comment]
The logger can be given [in the constructor](https://github.com/tuupola/cors-middleware#logger).

```php
$logger = Monolog\Logger("slim");
$rotating = new RotatingFileHandler(__DIR__ . "/logs/slim.log", 0, Logger::DEBUG);
$logger->pushHandler($rotating);

$app->add(new Tuupola\Middleware\CorsMiddleware([
    "logger" => $logger,
]));
```
