### ISSUE TITLE
Zend Expressive Don't work CORS

### ISSUE THREAD

**Issue by lpj145** [tuupola/cors-middleware#6]
On last version of zend expressive
https://docs.zendframework.com/zend-expressive/

The cors not works right!

When i:
![image](https://user-images.githubusercontent.com/11980109/30571540-eb8b9252-9cbe-11e7-933d-6e43f700ddd9.png)

![image](https://user-images.githubusercontent.com/11980109/30571550-f656dc50-9cbe-11e7-8f2a-9f98ac4786e6.png)

i think it not pass to cors on next function.

**Comment by tuupola** [comment]
The above does not to be from my cors middleware?

**Comment by lpj145** [comment]
above is a simple cors middleware, i can't implement you middleware.

**Comment by lpj145** [comment]
please see it:
https://gist.github.com/lpj145/cd2d8760ee08fb5ab9db4e05ed68b329#file-tuupolacors-php-L53

**Comment by tuupola** [comment]
Ah yes now I understand. There is no PSR-15 support yet because PSR-15 is not finalized. However Expressive has a [PSR-15 wrapper](https://github.com/zendframework/zend-stratigility/blob/master/src/Middleware/CallableMiddlewareWrapper.php) for PSR-7 style middlewares.

**Comment by lpj145** [comment]
oh, its song good for me, i need make factory to do it ?

**Comment by Xerkus** [comment]
Zend Expressive 2 wraps automatically, actually it is Zend Stratigility that does the wrapping, so it just works, nothing else needs to be done.
https://github.com/zendframework/zend-stratigility/blob/master/src/MiddlewarePipe.php#L135
and 
https://github.com/zendframework/zend-stratigility/blob/master/src/MiddlewarePipe.php#L224

**Comment by tuupola** [comment]
@Xerkus that is what I thought.

@lpj145 Can you show example code how you initialise the middleware and an example curl request which fails. For example:

```
$ curl "https://api.example.com/foo" \
    --request OPTIONS \
    --include \
    --header "Origin: http://www.example.com" \
    --header "Access-Control-Request-Method: PUT" \
    --header "Access-Control-Request-Headers: Authorization, If-Match"
```

**Comment by lpj145** [comment]
![image](https://user-images.githubusercontent.com/11980109/30605019-071489dc-9d43-11e7-8369-dcbeaf2db849.png)

**Comment by lpj145** [comment]
![image](https://user-images.githubusercontent.com/11980109/30605072-2c340080-9d43-11e7-8e74-e2d16b78b19c.png)

**Comment by tuupola** [comment]
Copy pasting code is preferred over screenshots. When testing copy paste my command exactly except the url. For example you should use `--header "Origin: http://www.example.com"` not `--header "Origin: http//:www.example.com"`

**Comment by lpj145** [comment]
curl lvh.me/ -v --request OPTIONS --include --header "Origin: http://www.example.com" --header "Access-Control-Request-Method: PUT"

**Comment by tuupola** [comment]
You can use three ` characters to format the code.

**Comment by lpj145** [comment]
![image](https://user-images.githubusercontent.com/11980109/30607561-e0f6cd4c-9d4b-11e7-9387-a84dcf3a8685.png)

`curl lvh.me/ -v --request OPTIONS --include --header "Origin: ht" --header "Access-Control-Request-Method: PUT"`

**Comment by lpj145** [comment]
I'm very grateful for that.

**Comment by tuupola** [comment]
I just tested with the latest Expressive and everything seems to be working as exptected. Code copied from examples.

```php
<?php

use Interop\Http\ServerMiddleware\DelegateInterface;
use Zend\Diactoros\Response\TextResponse;
use Zend\Expressive\AppFactory;

chdir(dirname(__DIR__));
require "vendor/autoload.php";

$app = AppFactory::create();

$app->get("/", function ($request, DelegateInterface $delegate) {
    return new TextResponse("Hello, world!");
});

$app->pipe(new Tuupola\Middleware\Cors([
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    "headers.allow" => [],
    "headers.expose" => [],
    "credentials" => false,
    "cache" => 0,
]));

$app->pipeRoutingMiddleware();
$app->pipeDispatchMiddleware();
$app->run();
```

```
curl http://localhost:8081 --include --header "Origin: http://example.com"
HTTP/1.1 200 OK
Host: localhost:8081
Date: Wed, 20 Sep 2017 13:09:03 +0000
Connection: close
X-Powered-By: PHP/7.1.6
Content-Type: text/plain; charset=utf-8
Access-Control-Allow-Origin: http://example.com
Vary: Origin

Hello, world!
```
