### ISSUE TITLE
Access-Control-Allow-Headers isn't being returned by the preflight request?

### ISSUE THREAD

**Issue by 2blane** [tuupola/cors-middleware#7]
The preflight request returns with a status of 200 OK, the problem is the header "Access-Control-Allow-Headers" isn't being returned so when the real request is made the browser doesn't send along the headers I want it to. I also tested this using curl and terminal, and if I send the real request with curl and the custom headers everything works like it's supposed to so it has something to do with this library. Are there certain circumstances where "Access-Control-Allow-Headers" isn't returned?

```
$cors = new \Tuupola\Middleware\Cors([
    "origin" => ["https://test.myapp.com"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    "headers.allow" => ["Referer", "User-Agent", "Authorization", "X-Requested-With", "Origin", "Headers", "Method", "Content-Type", "Accept", "X-CSRF-TOKEN"],
    "headers.expose" => ["Referer", "User-Agent", "Authorization", "X-Requested-With", "Origin", "Headers", "Method", "Content-Type", "Accept", "X-CSRF-TOKEN"],
    "credentials" => true,
    "cache" => 0,
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]);
$app->add($cors);
```

**Comment by tuupola** [comment]
If curl request is working but browser request is not you could check from the browsers developer console what kind of request browser is making. If the results are different the also the requests are somehow different.

**Comment by 2blane** [comment]
Figured out the issue. It is related to #2. Basically, the browser was showing that there was an error with CORS because the headers weren't being set when there is an exception so I thought it was a CORS error and turns out to be an issue with how Slim handles exceptions.
