### ISSUE TITLE
CorsMiddleware is now generic - by accident?

### ISSUE THREAD

**Issue by InvisibleSmiley** [tuupola/cors-middleware#78]
Since version 1.4.0, CorsMiddleware is now generic because @template was added to the class PHPDoc. That means all users of the class must specify template parameter TSanitizedOptions when using a static analyzer like PHPStan above a certain level (i.e. with generics support/checks enabled).

I was unable to find an example how/why this template parameter should be specified and what the reason and anticipated benefit was of making CorsMiddleware generic. I suspect that this was done by accident and what you really wanted is to define and use local type aliases:
https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases

Example of how the current implementation results in a PHPStan error that was not present before:
https://phpstan.org/r/381821ff-52e4-491d-afc8-4832e219d28b

**Comment by InvisibleSmiley** [comment]
The changes I refer to here were introduced through pull request 63.

**Comment by tuupola** [comment]
I am not sure why the template is there but I will remove it.

**Comment by tuupola** [comment]
Released as 1.4.3
