### ISSUE TITLE
Middleware not adding headers on an options/pre-flight call?

### ISSUE THREAD

**Issue by eneropp-dave** [tuupola/cors-middleware#8]
Hi,

I am still working on the project I raised and closed an earlier issue for and am now having CORS problems again but struggling to work out why. The summary of what I "think" is happening is:

- The app is sending a custom header which I haven't managed to find yet on a POST, which causes it to make a pre-flight/options call to check what is allowed. (this is nothing to do with SLIM obviously). I have found that I can 'break' the headers with an incorrect attempt to set them and the calls work ok, SLIM responds to the POST with the correct headers.

- The SLIM middleware is not responding to the OPTIONS call with the same headers as it is for POST calls, I have the middleware installed and logging so when normal calls come in I see the logs, but I never see anything for a pre-flight call which even if it was responding differently, I'd expect to see as log entry.

Point 1 above I need to sort out myself and am doing so in parallel. Point 2 I would really like some help to work out why SLIM isn't invoking the middleware for a pre-flight call.

More details below the line.

-------------------------
Using Slim 3.8.1 with Cors-Middleware 0.5.2. I'm trying to develop the UI with Ionic (via Ionic Creator) so using AngularJS. Using inspect I can see the headers being set on the POST as below, but the OPTIONS one seems to return different headers:

**Response when I allow headers to go correctly and results in an OPTIONS call:**
```
Request URL:https://<mydomain>.azurewebsites.net/logon
Request Method:OPTIONS
Status Code:200 OK
Remote Address:<ip_removed>:443
Referrer Policy:no-referrer-when-downgrade
```
Response Headers
```
Allow:OPTIONS, TRACE, GET, HEAD, POST
Content-Length:0
Date:Mon, 02 Oct 2017 12:38:42 GMT
Public:OPTIONS, TRACE, GET, HEAD, POST
Server:Microsoft-IIS/8.0
Set-Cookie:ARRAffinity=71348a31a0fb1ab0cb27394a14e292875f39c36acbe2721cdaa782e123565e70;Path=/;HttpOnly;Domain=<mydomain>.azurewebsites.net
X-Powered-By:ASP.NET
```

**Response below when I 'break' the headers and it doesnt result in a pre-flight check:**
```
Request URL:https://<mydomain>.azurewebsites.net/dashboard
Request Method:POST
Status Code:200 OK
Remote Address:<ip_removed>:443
Referrer Policy:no-referrer-when-downgrade
```
Response Headers
```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://creator.ionic.io
Access-Control-Expose-Headers:Authorization
Access-Control-Expose-Headers:Accept
Access-Control-Expose-Headers:Content-Type
Access-Control-Expose-Headers:Origin
Cache-Control:no-store, no-cache, must-revalidate
Content-Encoding:gzip
Content-Length:431
Content-Type:application/json;charset=utf-8
Date:Mon, 02 Oct 2017 13:09:51 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:Microsoft-IIS/8.0
Vary:Origin,Accept-Encoding
X-Powered-By:ASP.NET
X-Powered-By:PHP/7.0.23
```
Note I know that there are a couple of things I need to hide there once I get to the bottom of this issue such as ASP.NET and PHP but not worried about it at this stage.

I've implemented the middleware as below, I've added a few permitted origins including evil.com due to using browser extension for debugging, I get the issues when that is switched off:

```
$app->add(new \Tuupola\Middleware\Cors([
  "origin" => ["https://creator.ionic.io", "http://evil.com", "http://<my_domain>.azurewebsites.net", "https://<my_domain>.azurewebsites.net"],
  "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  "headers.allow" => ["Content-Type", "Authorization", "Accept", "Origin"],
  "headers.expose" => ["Content-Type", "Authorization", "Accept", "Origin"],
  "credentials" => true,
  "cache" => 0,
]));
```

Have I missed something that is obvious in how to make it fire the middleware on the OPTIONS or preflight request?

It appears to me that the lack of any log entry on an OPTIONS and the different headers returned may point to the middleware just not being invoked on an OPTIONS call but its a guess

**Comment by tuupola** [comment]
> It appears to me that the lack of any log entry on an OPTIONS and the different headers returned may point to the middleware just not being invoked on an OPTIONS call but its a guess

Sounds like the request is not even handled by Slim. Looking at the the example headers there is for example:

```
Server:Microsoft-IIS/8.0
X-Powered-By:ASP.NET
```

Maybe IIS or ASP somehow captures the requests?  In any case to be able to debug I need example curl command line request and the response headers. For example:

```
$ curl "https://api.example.com/" \
    --request OPTIONS \
    --include
    --header "Access-Control-Request-Method: PUT" \
    --header "Origin: http://www.example.com"

HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://www.example.com
Vary: Origin
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE
```

**Comment by eneropp-dave** [comment]
Thanks Mika, yep that sounds like a reasonable hypothesis - I will do some digging and see if I can find why that might be.

In the mean time I have also run the CURL request (running from windows using Confused By Code's tool: http://www.confusedbycode.com/curl/#downloads):

Request:
`curl "https://eneroppdemoapi01.azurewebsites.net/logon" --request OPTIONS --include --header "Access-Control-Request-Method: POST" --header "Origin: http://localhost"`

Response is:
```
HTTP/1.1 200 OK
Allow: OPTIONS, TRACE, GET, HEAD, POST
Content-Length: 0
Server: Microsoft-IIS/8.0
Public: OPTIONS, TRACE, GET, HEAD, POST
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=71348a31a0fb1ab0cb27394a14e292875f39c36acbe2721cdaa782e123565e70;Path=/;HttpOnly;Domain=eneroppdemoapi01.azurewebsites.net
Date: Mon, 02 Oct 2017 14:27:00 GMT
```
As expected - no logging from the middleware or SLIM at all, so I suspect you are right, I'll update if I find anything further. Any ideas always welcome obviously

**Comment by eneropp-dave** [comment]
As an update if anyone else is hosting in a similar environment, Mika you were right on it not hitting SLIM, the reason being that IIS grabs it and processes. In order to force the OPTIONS request all the way through the SLIM I needed to add the below to the web.config on the server:

<system.webServer>
	<modules runAllManagedModulesForAllRequests="true">
	  <remove name="WebDAVModule" />
	</modules>  
	<handlers>
	   <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
	   <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />
	   <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
	   <remove name="WebDav" />
	   <remove name="OPTIONSVerbHandler" />
	   <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0" />
	   <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0" />
	   <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
	</handlers>        
</system.webServer>

Now when I run the same CURL command I get a different response, which looks like the method type of options in not allowed. I am not seeing anything in the logs still for SLIM / middleware but it's getting further in.
```
HTTP/1.1 405 Method Not Allowed
Allow: GET, HEAD, OPTIONS, TRACE
Content-Length: 101
Content-Type: text/html
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=71348a31a0fb1ab0cb27394a14e292875f39c36acbe2721cdaa782e123565e70;Path=/;HttpOnly;Domain=eneroppdemoapi01.azurewebsites.net
Date: Mon, 02 Oct 2017 14:38:23 GMT

The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used.
```
I also get the same error when I call it from the Ionic Creator tool which is encouraging.

**Comment by eneropp-dave** [comment]
Finally found exactly what I needed to add to the Web Config, with a combination of:

- https://stackoverflow.com/questions/30346907/how-to-remove-webdav-module-from-iis
- https://stackoverflow.com/questions/22495240/iis-hijacks-cors-preflight-options-request

Attaching the web.config in case it is of any use to someone. Mika, it may be worth a note on the repo or this page: https://www.slimframework.com/docs/start/web-servers.html to the effect that if using the CORS middleware you need more than just the config on the web-servers page at present to make it work.

Obviously if someone is using PHP 5.6 then the line below needs updating (or if it is in a different location):

`D:\Program Files (x86)\PHP\v7.0\php-cgi.exe`

[web.config.txt](https://github.com/tuupola/cors-middleware/files/1349304/web.config.txt)

Thanks for the initial suggestion Mika, I have been playing with this for almost 3 days now, finally working no problem.

Cheers
Dave
