### ISSUE TITLE
If HTTP_ORIGIN is present but empty/null

### ISSUE THREAD

**Issue by eneropp-dave** [tuupola/cors-middleware#9]
I have an odd condition, using a preview app on the phone (Ionic Creator) to view a project. For some reason it seems to be sending the origin header as below according to my logging:

	"HTTP_ORIGIN": ["null"],

When I package the app as an APK it sends no Origin header as you would expect, or if I run it off a webserver it sets a valid one, this android app is mainly for demos prior to actually building the full app and it appears to somehow set the header to empty or null, I can't work out what the middleware is trying to do with that scenario though, I see the logging as below:

**When installed as APK (no origin header)**
[2017-10-05 04:56:42] slim-app.DEBUG: CORS analysis for request started. [] {"uid":"76cb749"}
[2017-10-05 04:56:42] slim-app.WARNING: Origin header URL cannot be parsed. {"url":"file://"} {"uid":"76cb749"}
[2017-10-05 04:56:42] slim-app.INFO: Request is not CORS (request origin is empty). {"request":null,"server":"[object] (Neomerx\\Cors\\Http\\ParsedUrl: ://)"} {"uid":"76cb749"}
[2017-10-05 04:56:42] slim-app.DEBUG: CORS analysis for request completed. [] {"uid":"76cb749"}

**When using the creator android app** (empty origin header)
[2017-10-05 04:57:33] slim-app.DEBUG: CORS analysis for request started. [] {"uid":"a2fd7a4"}
[2017-10-05 04:57:33] slim-app.INFO: Request is not CORS (request origin equals to server one). Check config settings for Server Origin. {"request":"[object] (Neomerx\\Cors\\Http\\ParsedUrl: )","server":"[object] (Neomerx\\Cors\\Http\\ParsedUrl: ://)"} {"uid":"a2fd7a4"}
[2017-10-05 04:57:33] slim-app.DEBUG: CORS analysis for request completed. [] {"uid":"a2fd7a4"}

It appears to decide it is not CORS but logs "request origin equals to server one" and I can't find where it is logging that in the source. I'd ideally like to include in the middleware an acceptance of the condition of HTTP_ORIGIN being set but empty, or just to delete the header. I have tried the settings below through trial and error but none seem to let it flow through:

```
"origin" => [
"null",
"",
null,
,]
```
Any thoughts?

**Comment by tuupola** [comment]
Without `Origin: something` request header the request is not a CORS request and middleware will ignore it. Not sure if sending empty `Origin:` header is even valid but it at least feels wrong. The logic is somewhere in [neomerx/cors-psr7](https://github.com/neomerx/cors-psr7).

Instead of altering that code you could also create a middleware which removes the `Origin:` header if it is empty.

**Comment by eneropp-dave** [comment]
Thanks Mika,

You are right, it does feel wrong. I tried to put some middleware in to
remove the header if it was empty and realised is is actually being set to
a string of null (not a null string but actually "null") which feels even
worse. While doing this I noticed that the request is arriving as an
OPTIONS not a POST, so I presume even though the request is not CORS it is
somehow generating a pre-flight check, annoyingly I cannot see the server
that is sending the request so can't tell exactly what it is doing.

Basically the App on my phone, connects to their server and previews a
HTML5 site as if it were an installed app, their site then acts similarly
to a reverse proxy and makes the calls to my API so even though I have
control of the app, the API and my webserver, I don't have control of the
middle step. It is very useful to avoid non-technical customers needing to
download and install APKs etc just to see the app but makes troubleshooting
hard.

I have added some middleware which strips the ORIGIN header if is
empty/null/set to a string of null and it is not generating a CORS request,
but is still being received at the API as an OPTIONS, I suspect either they
are explicitly sending it or something else is happening to cause it to
fail the pre-flight, just can't find what.

I'll keep this one open for now and feedback onto it once I work out whats
happening just so it stays as information for anyone else who happens to do
something similar, if you have any ideas for troubleshooting I'd love any
pointers as well.

Thanks
Dave



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Regards,

*Dave Hodgson*
Customer Technology Co-Founder
*M*. +447731842770
*E*. dave.hodgson@eneropp.com
*E. *www.eneropp.com

Eneropp <http://www.eneropp.com> Mobilizing Energy Utility Online Services

**Comment by neomerx** [comment]
@eneropp-dave Hi, have you got any news on that? If you have any questions on how CORS works feel free to ask.

Earlier you asked about a place where the logs are written. [Here it is.](https://github.com/neomerx/cors-psr7/blob/master/src/Analyzer.php#L153-L157) and that's the [code implementing origin comparison](https://github.com/neomerx/cors-psr7/blob/master/src/Analyzer.php#L331-L347).
